sudo: required
dist: xenial

os:
  - linux
  - osx
  - windows

language: go
go:
  - 1.x

matrix:
  include:
    - os: osx
      install:
        - go get -d -t -v ./...
        - sh build-osx.sh
    - os: linux
      install:
        - go get -d -t -v ./...
        - sh build-linux.sh
    - os: windows
      install:
        - go get -d -t -v ./...
        - sh build-windows.bat
